type User {
  id: Int!
  firstName: String
  lastName: String
  username: String!
  email: String!
  isActive: Boolean
  created_at: Int!
  posts: [Post]
}

input CreateUserInput {
  email: String!
  username: String
  firstName: String
  lastName: String
}

input UpdateUserInput {
  id: Int!
  firstName: String
  lastName: String
  username: String
  email: String
}

type Post {
  id: Int!
  title: String!
  votes: Int
  authorId: Int!
  created_at: Int!
}

input CreatePostInput {
  title: String!
  authorId: Int!
}

input UpdatePostInput {
  id: Int!
  title: String!
  authorId: Int!
}

type Query {
  userById(id: Int!): User
  users: [User]!
  getUsersByFirstAndLast(firstName: String, lastName: String = ""): [User]

  postById(id: Int!): Post
  posts: [Post]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(input: UpdateUserInput!): User!
  deleteUser(userId: Int!): User!

  createPost(input: CreatePostInput!): Post!
  updatePost(input: UpdatePostInput!): Post!
  upvotePost(postId: Int!): Post!
  deletePost(postId: Int!): Post!
}

type Subscription {
  createdPost(input: String!): Post!
}
