version: '3.9'

services:
  redis_storage:
    image: redis
    restart: always
    command: redis-server --save 5 1 --loglevel warning
    ports:
      - 6350:6379
    volumes:
      - redis_storage_data:/data

  postgress_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: db_pass
      POSTGRES_USER: db_user
      POSTGRES_DB: graphql_shop
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5486:5432

volumes:
  redis_storage_data:
  postgres_data:
